# Generated by Django 3.0.7 on 2020-06-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20200627_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='xml',
            field=models.FileField(upload_to=''),
        ),
    ]
