# Generated by Django 2.1.7 on 2020-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_auto_20200627_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.CharField(default='xxx', max_length=256),
        ),
    ]
