# Generated by Django 2.1.7 on 2020-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20200627_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pht',
            field=models.TextField(default='xxx'),
        ),
    ]
